# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
#   'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# -------------------------------------
# Site Settings
# -------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title  }}, {{ site.email  }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable  }}.

name: Sangam Kumar
title: Improve Lint Bear Quality
description: Tracking progress of coala project for Google Summer of Code 2018
email: ksangam68@gmail.com

gh_name: sangamcse
gh_commits: https://github.com/coala/coala-bears/commits/?author=sangamcse
gh_prs: https://github.com/coala/coala-bears/pulls?utf8=%E2%9C%93&q=is:pr+author:sangamcse
gh_issues: https://github.com/coala/coala-bears/issues?utf8=%E2%9C%93&q=is:issue+author:sangamcse
gh_project: https://github.com/coala/coala-bears

# -------------------------------------
# Build Settings
# -------------------------------------
markdown: kramdown
future: true
encodig: utf-8
highlighter: rouge
